name: DOD
favicon: null
layout_spectrum: 0.8
title: The Wizard Switch
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#ffffff'
    - '#362f2d'
    - '#000000'
    - '#d3d1d1'
    - '#a5a2a1'
  brandStrength: 1
  lightness: 0.5
  saturation: 0.5
  rhythmicContrast: 0.5
purpose:
  - name: sign-ups
    item: null
    url: null
